use crate::config::{FirestoreConfig, ServiceAccountKey};
use crate::speedtest::SpeedtestResult;
use anyhow::{bail, Context, Result};
use jsonwebtoken::{encode, Algorithm, EncodingKey, Header};
use serde::{Deserialize, Serialize};
use std::time::{SystemTime, UNIX_EPOCH};

const DATASTORE_SCOPE: &str = "https://www.googleapis.com/auth/datastore";

/// JWT claims used in the Service Account bearer token flow (RFC 7523).
#[derive(Debug, Serialize)]
struct Claims {
    iss: String,
    scope: String,
    aud: String,
    iat: u64,
    exp: u64,
}

#[derive(Debug, Deserialize)]
struct TokenResponse {
    access_token: String,
}

/// Exchanges a signed Service Account JWT for an OAuth2 access token.
///
/// Follows the "JWT Bearer" flow: signs a JWT with the private key and POSTs
/// it to the Google token endpoint. No browser interaction required.
///
/// # Arguments
/// * `config` - Firestore settings containing the Service Account key path.
///
/// # Errors
/// Returns an error if the key file cannot be read, the JWT cannot be signed,
/// or the token endpoint rejects the request.
pub async fn get_access_token(config: &FirestoreConfig) -> Result<String> {
    let key = ServiceAccountKey::load(&config.service_account_key_path)?;

    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .context("Failed to read system clock")?
        .as_secs();

    let claims = Claims {
        iss: key.client_email.clone(),
        scope: DATASTORE_SCOPE.to_string(),
        aud: key.token_uri.clone(),
        iat: now,
        exp: now + 3600,
    };

    let header = Header::new(Algorithm::RS256);
    let encoding_key = EncodingKey::from_rsa_pem(key.private_key.as_bytes())
        .context("Invalid private key in service-account.json")?;

    let jwt = encode(&header, &claims, &encoding_key)
        .context("Failed to sign the JWT")?;

    let client = reqwest::Client::new();
    let response = client
        .post(&key.token_uri)
        .form(&[
            ("grant_type", "urn:ietf:params:oauth:grant-type:jwt-bearer"),
            ("assertion", jwt.as_str()),
        ])
        .send()
        .await
        .context("Failed to call the Google token endpoint")?;

    let status = response.status();
    let body = response.text().await.unwrap_or_default();

    if !status.is_success() {
        bail!("Google rejected authentication ({}): {}", status, body);
    }

    let token: TokenResponse = serde_json::from_str(&body)
        .with_context(|| format!("Unexpected response from token endpoint: {}", body))?;

    Ok(token.access_token)
}

/// Appends a speedtest result as a new document to the Firestore collection.
///
/// Uses the Firestore REST API v1. The document ID is auto-generated by Firestore.
///
/// # Arguments
/// * `config` - Firestore connection settings (project ID, collection name).
/// * `token` - OAuth2 bearer token obtained via [`get_access_token`].
/// * `result` - Parsed speedtest measurement to persist.
///
/// # Errors
/// Returns an error if the HTTP request fails or Firestore rejects the document.
pub async fn append_document(
    config: &FirestoreConfig,
    token: &str,
    result: &SpeedtestResult,
) -> Result<()> {
    let url = format!(
        "https://firestore.googleapis.com/v1/projects/{}/databases/speedtest-monitordb-one/documents/{}",
        config.project_id, config.collection
    );

    let body = serde_json::json!({
        "fields": {
            "timestamp":       { "timestampValue": result.timestamp.to_rfc3339() },
            "download_mbps":   { "doubleValue": result.download_mbps },
            "upload_mbps":     { "doubleValue": result.upload_mbps },
            "ping_ms":         { "doubleValue": result.ping_ms },
            "jitter_ms":       { "doubleValue": result.jitter_ms },
            "packet_loss_pct": { "doubleValue": result.packet_loss_pct },
            "server":          { "stringValue": result.server },
            "isp":             { "stringValue": result.isp },
            "external_ip":     { "stringValue": result.external_ip },
            "result_url":      { "stringValue": result.result_url }
        }
    });

    let client = reqwest::Client::new();
    let response = client
        .post(&url)
        .bearer_auth(token)
        .json(&body)
        .send()
        .await
        .context("Failed to call the Firestore API")?;

    let status = response.status();
    if !status.is_success() {
        let body = response.text().await.unwrap_or_default();
        bail!("Firestore API returned an error ({}): {}", status, body);
    }

    Ok(())
}
